# Mission Name & Desc
jcms.slaughterhouse=Tapamaja
jcms.slaughterhouse_desc=Sa pead hunniku vaenlasi maha laskma ilma mingi erilise põhjuseta. Lihtsalt ära lase oma meeskonnakaaslasi.

# Mission Objectives
jcms.obj_slaughterhousekilltotal=Tapetud

# Mission Notifications
jcms.25complete=Ilmumissagedus Kolmekordistatud
jcms.50complete=Ilmumissagedus Neljakordistatud
jcms.75complete=Ilmumissagedus Viiekordistatud