# Mission Name & Desc
jcms.slaughterhouse=Kesimhane
jcms.slaughterhouse_desc=Bir sürü NPC'yi hiçbir sebep olmadan vurup öldürmen gerekecek. Sadece takım arkadaşlarına vurma yeter.

# Mission Objectives
jcms.obj_slaughterhousekilltotal=Katledildi

# Mission Notifications
jcms.25complete=Spawn oranı üçe katlandı
jcms.50complete=Spawn oranı dörde katlandı
jcms.75complete=Spawn oranı beşe katlandı