# Mission Name & Desc
jcms.slaughterhouse=Скотобойня
jcms.slaughterhouse_desc=Вам придется застрелить кучу НПС без особой причины. Только не стреляйте в своих товарищей по команде.

# Mission Objectives
jcms.obj_slaughterhousekilltotal=Убитые

# Mission Notifications
jcms.25complete=Скорость появления увеличилась в три раза
jcms.50complete=Скорость появления увеличилась в четыре раза
jcms.75complete=Скорость появления увеличилась в пять раз