jcms.totalcontrol=Полный Контроль
jcms.totalcontrol_desc=Найдите и захватите все зоны, чтобы распространить влияние J-Corp. Враги внутри зоны будут останавливать прогресс. Больше игроков в зоне — быстрее прогресс.

jcms.monopolytakeover=Монополия
jcms.monopolytakeover_desc=RGG установили игровые терминалы в этом районе. Превратите их в бизнесы J-Corp и зарабатывайте доход! Каждый бизнес будет приносить что-то полезное. Отправляйте отчёты обратно в J-Corp, чтобы доказать, что дела идут в гору!

jcms.blackout=Блэкаут
jcms.blackout_desc=Мир погрузился во тьму, из-за чего все зачистщики стали уязвимее к урону. Активируйте светогенераторы, чтобы уменьшить получаемый урон и вновь осветить территорию.

jcms.obj_controlzone=Удерживайте и контролируйте зону
jcms.obj_hackcasinoterminal=Взломайте казино-терминал RGG
jcms.obj_businessreports=Отправьте бизнес-отчёты в J-Corp
jcms.obj_lightgenerator=Активируйте светогенераторы

jcms.zonecontrol=Контроль зоны
jcms.casinoterminal=Казино RGG
jcms.casinoterminalhacked=Бизнес J-Corp
jcms.lightgenerator=Светогенератор

jcms.terminal_rggscreen_title=R.G.G
jcms.terminal_rggscreen_os=GAMBLE O.S v
jcms.terminal_rggscreen_access=ПАНЕЛЬ ДОСТУПА
jcms.terminal_rggscreen_hackedtitle=J-Corp
jcms.terminal_rggscreen_hackedos=Business O.S 
jcms.terminal_rggscreen_hackedinstall=УСТАНОВИТЬ
jcms.terminal_rggscreen_hackedinstalled=УСТАНОВКА УСПЕШНА.

jcms.terminal_lightgen=Утилита генерации света
jcms.terminal_lightgenerror=[ Ошибка — требуется ремонт ]
jcms.terminal_lightgenfix=Ремонт успешен!
jcms.terminal_lightgenrepair=РЕМОНТ
jcms.terminal_lightgenactivate=АКТИВИРОВАТЬ
jcms.terminal_lightgenworking=[ ГЕНЕРАТОР АКТИВЕН ]

jcms.np_zone_capture_progress=ПРОГРЕСС ЗАХВАТА:
jcms.np_zone_defend=ЗАЩИЩАЙТЕ ЭТУ ЗОНУ ОТ ВРАГОВ.
jcms.np_zone_contested=ЗОНА ОСПАРИВАЕТСЯ. УСТРАНИТЕ АКТУАЛЬНЫЕ УГРОЗЫ.
jcms.np_zone_secured=ЗОНА ЗАХВАЧЕНА.

jcms.np_upgrade_1=Медицинская помощь J-Corp
jcms.np_upgrade_1_desc1=Меньше криков и смертей. Больше зачисток.
jcms.np_upgrade_1_desc2=+2 HP каждые 2 секунды

jcms.np_upgrade_2=Броня из налоговых документов
jcms.np_upgrade_2_desc1=Сделана из лучших и просроченных налоговых отчётов! Теперь никто
jcms.np_upgrade_2_desc2=не захочет к вам прикасаться!
jcms.np_upgrade_2_desc3=+20% к сопротивлению урону

jcms.np_upgrade_3=Крайне нелегальные боеприпасы
jcms.np_upgrade_3_desc1=К счастью, у J-Corp лучшие юристы, которых может купить жадность корпораций!
jcms.np_upgrade_3_desc2=+25% наносимого урона

jcms.np_upgrade_4=Ботинки RALAB
jcms.np_upgrade_4_desc1=Что означает RALAB? Ну, «Running away like a bitch» («Сбегать, как сука»).
jcms.np_upgrade_4_desc2=+25% к скорости передвижения

jcms.np_upgrade_5=Дополнительная награда
jcms.np_upgrade_5_desc1=Каждое 6-е убийство приносит дополнительные 45J.

jcms.np_upgrade_6=На внушение страха
jcms.np_upgrade_6_desc1=Пули, наполненные энергией J, вселяют страх в этих ублюдков из RGG.
jcms.np_upgrade_6_desc2=-20% урона от врагов, которых вы ранили, в течение 5 секунд.

jcms.np_upgrade_7=Улучшенная перезарядка щита
jcms.np_upgrade_7_desc1=Щиты восстанавливаются быстрее! Меньше бегства, как трус, и
jcms.np_upgrade_7_desc2=больше сражений лицом к лицу.
jcms.np_upgrade_7_desc3=+33% к скорости восстановления щита

jcms.np_upgrade_8=Приказы высокой важности
jcms.np_upgrade_8_desc1=Сокращает время между приказами на 33%.
