jcms.obj_generator=Найдите энергоблоки и зарядите генератор
jcms.generator=Генератор
jcms.generator_desc=После опасного задания силы врага обесточили эвакуационный портал. Зарядите генератор энергоблоками и убирайтесь с этой карты!
jcms.energy_block=Энерго блок

jcms.guntest=Полевые испытания
jcms.obj_gunget=Взломайте терминалы и получите образцы
jcms.obj_guntest=Испытайте все образцы оружия
jcms.obj_guntestkills=Убивайте врагов, чтобы испытать %s
jcms.guntest_desc=J corp создала новые образцы оружия, которым необходима проверка в полевых условиях. Получите вооружение в терминалах и испытайте его! Тестовые образцы можете оставить себе
jcms.terminal_guntestcontrols=ПОЛУЧЕНИЕ ОРУЖИЯ
jcms.terminal_guntestget=ПОЛУЧИТЬ
jcms.terminal_guntestgotten=ПОЛУЧЕНО
jcms.terminal_unlocked=ЗАБЛОКИРОВАНО!
jcms.terminal=Терминал
jcms.testing_weapon=Образец