# Mission Name & Desc
jcms.slaughterhouse=Slaughterhouse
jcms.slaughterhouse_desc=You're going to have to shoot a bunch of NPCs to death for no particular reason. Just don't shoot your teammates.

# Mission Objectives
jcms.obj_slaughterhousekilltotal=Slaughtered

# Mission Notifications
jcms.25complete=Spawnrate Tripled
jcms.50complete=Spawnrate Quadrupled
jcms.75complete=Spawnrate Quintupled