jcms.totalcontrol=Total Control
jcms.totalcontrol_desc=Find and control all zones to spread influence of J-Corp. Enemies inside the zone will halt progress. More players in the zone will speed up progress.

jcms.monopolytakeover=Monopoly
jcms.monopolytakeover_desc=The RGG have set up gambling termnials around this area. Turn them into J-Corp Businesses and earn income! Each business will provide something useful. Send reports back to J-Corp to prove business is booming!

jcms.blackout=Blackout
jcms.blackout_desc=Total Darkness has encased the world, giving all sweepers a damage vulnerability. Reactivate the Light-Generators to reduce damage taken and re-illuminate the area.

jcms.obj_controlzone=Hold and Control the Zone
jcms.obj_hackcasinoterminal=Hack RGG Casino Terminal
jcms.obj_businessreports=Send Business Reports to J-Corp
jcms.obj_lightgenerator=Reactivate the Light Generators

jcms.zonecontrol=Control Zone
jcms.casinoterminal=RGG Casino
jcms.casinoterminalhacked=J-Corp Business
jcms.lightgenerator=Light Generator

jcms.terminal_rggscreen_title=R.G.G
jcms.terminal_rggscreen_os=GAMBLE O.S v
jcms.terminal_rggscreen_access=ACCESS PANEL
jcms.terminal_rggscreen_hackedtitle=J-Corp
jcms.terminal_rggscreen_hackedos=Business O.S 
jcms.terminal_rggscreen_hackedinstall=INSTALL
jcms.terminal_rggscreen_hackedinstalled=INSTALL SUCCESSFUL.

jcms.terminal_lightgen=Light Generation Utility
jcms.terminal_lightgenerror=[ Error - Repair Required ]
jcms.terminal_lightgenfix=Repair Successful!
jcms.terminal_lightgenrepair=REPAIR
jcms.terminal_lightgenactivate=ACTIVATE
jcms.terminal_lightgenworking=[ GENERATOR ACTIVE ]

jcms.np_zone_capture_progress=CAPTURE PROGRESS:
jcms.np_zone_defend=DEFEND THIS ZONE FROM ENEMIES.
jcms.np_zone_contested=ZONE CONTESTED. ELIMINATE CURRENT THREATS.
jcms.np_zone_secured=ZONE SECURED.

jcms.np_upgrade_1=J-Corp Medical Care
jcms.np_upgrade_1_desc1=Less crying and dying. More Sweeping.
jcms.np_upgrade_1_desc2=+2HP regenerated every 2 seconds

jcms.np_upgrade_2=Tax Document Armor
jcms.np_upgrade_2_desc1=Made with our finest and overdue tax reports! No one will want to
jcms.np_upgrade_2_desc2=touch you now!
jcms.np_upgrade_2_desc3=+20% Damage Resistance

jcms.np_upgrade_3=Highly Illegal Munitions
jcms.np_upgrade_3_desc1=Thankfully, J-Corp has the best lawyers corporate greed can buy!
jcms.np_upgrade_3_desc2=+25% Damage Dealt

jcms.np_upgrade_4=RALAB Boots
jcms.np_upgrade_4_desc1=What does RALAB stand for? Well, 'Running away like a bitch'.
jcms.np_upgrade_4_desc2=+25% Movement Speed

jcms.np_upgrade_5=Bonus Bounty
jcms.np_upgrade_5_desc1=Every 6th kill grants an additional 45J.

jcms.np_upgrade_6=Fear Inducing
jcms.np_upgrade_6_desc1=Sheer J infused bullets inflict fear onto those RGG scum.
jcms.np_upgrade_6_desc2=-20% Damage Taken by enemies you damage for 5 seconds.

jcms.np_upgrade_7=Improved Recharge
jcms.np_upgrade_7_desc1=Shields recharge faster! Less running away like a coward and
jcms.np_upgrade_7_desc2=more facing enemies head on.
jcms.np_upgrade_7_desc3=+33% Shield Recharge Rate

jcms.np_upgrade_8=High Priority Orders
jcms.np_upgrade_8_desc1=Speeds up time between orders by 33%.