jcms.obj_generator=Find energy blocks and charge the generator by them
jcms.generator=Generator  
jcms.generator_desc=After a dangerous mission, enemy forces disabled the evacuation portal. Power up the generator with energy blocks and get off this map!  
jcms.energy_block=Energy Block  

jcms.guntest=Field Trials
jcms.obj_gunget=Breach the terminals to get weapon prototypes
jcms.obj_guntest=Test all weapon prototypes
jcms.obj_guntestkills=Eliminate enemies to test %s
jcms.guntest_desc=J Corp has developed new weapon prototypes that require field testing. Collect the gear from terminals and put it to the test! You may keep the trial samples afterward
jcms.terminal_guntestcontrols=WEAPON DISPENSING
jcms.terminal_guntestget=DISPENSE
jcms.terminal_guntestgotten=DISPENSED
jcms.terminal_unlocked=LOCKED!
jcms.terminal=Terminal
jcms.testing_weapon=Prototype