# Mission Name & Desc
jcms.slaughterhouse=Slaughterhouse
jcms.slaughterhouse_desc=Ye're goin' t' 'ave t' shoot a bunch o' NPCs t' death fer no particular reason. Jus' don't shoot yer teammates.

# Mission Objectives
jcms.obj_slaughterhousekilltotal=Slaughtered

# Mission Notifications
jcms.25complete=Spawnrate Tripled
jcms.50complete=Spawnrate Quadrupled
jcms.75complete=Spawnrate Quintupled